Refactoring

diff --git a/data/www/htdocs/api/stop-stream b/data/www/htdocs/api/stop-stream
--- a/data/www/htdocs/api/stop-stream
+++ b/data/www/htdocs/api/stop-stream
@@ -1,20 +1,12 @@
 #!/bin/bash
 
-echo "Content-type: text/html"
-echo
-
 while read line
 do
-  eval export ${line}
+  eval export "${line}"
 done<${REQUEST_BODY_FILE}
 
 hls_dir="/tmp/htdocs/${hash}"
 
-if [[ -f ${hls_dir}/pid ]]
-then
-	pid=$(cat ${hls_dir}/pid)
-	kill ${pid}
-	echo "0"
-else
-	echo "1"
-fi
+kill $(lsof | grep "${hls_dir}/ffmpeg.log" | cut -f1 | xargs) || true
+
+echo "0" | error/200
